### ISSUE TITLE
Проверить тип данных при загрузке маппинга

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#41]
Прецедент
Загружается маппинг с указанными типами данных в колонках
![image](https://user-images.githubusercontent.com/36114863/45103922-9bcdad00-b139-11e8-83af-1e5d4771f3de.png)
После загрузки, есть все, кроме типов данных
![image](https://user-images.githubusercontent.com/36114863/45104022-c881c480-b139-11e8-9e88-7cc7c7eeeed8.png)
В форме редактирования колонки тип тоже не указан
![image](https://user-images.githubusercontent.com/36114863/45104066-df281b80-b139-11e8-9cf8-5a5e98ebd5c2.png)
Ожидаемое поведение:
В виде настроки маппинга и в виде настройки колонки тип данных указан.

**Comment by ybinzu** [comment]
Глюк интерфейса, на самом деле все импортируется отлично с загруженного маппинга, просто тип данных не показывается.
