### ISSUE TITLE
Импорт данных без номера конечного Protocol (номер УИК)

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#45]
При импорте файла "Дагестан 2016 Мятлев.xlsx" https://drive.google.com/file/d/1oBPmtFHCuo9DKdcQIlIgyfotfj2pmDso/view?usp=sharing
сервер выдает ошибку. 
Таблица данных отличается тем, что тут нет Номера УИК. Вся иерархия описывается данными типа String.

**Comment by ybinzu** [comment]
Ошибка была связана с #44. Проверил при помощи тестов: 90f02e8

**Comment by ybinzu** [comment]
Пример импорта без номера УИК:
Protocols:
<img width="684" alt="screen shot 2018-09-06 at 11 48 18" src="https://user-images.githubusercontent.com/1109847/45146699-0a5b4b00-b1cc-11e8-9477-62bae0dd9daf.png">

LineNumbers:
<img width="330" alt="screen shot 2018-09-06 at 11 48 51" src="https://user-images.githubusercontent.com/1109847/45146700-0a5b4b00-b1cc-11e8-8ae1-b2b828b341ae.png">
