### ISSUE TITLE
Сделать осмысленный порядок для выбора строк протокола

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#51]
При выборе параметра для анализа, Пользователь видит их в самом непредсказуемом порядке.
![image](https://user-images.githubusercontent.com/36114863/45222871-54bcf480-b2be-11e8-9cd5-fdd458bf631e.png)
![image](https://user-images.githubusercontent.com/36114863/45222882-5e465c80-b2be-11e8-9765-a48e3eb0f951.png)
![image](https://user-images.githubusercontent.com/36114863/45222903-68685b00-b2be-11e8-8644-947ee1921b37.png)

Можно, чтобы не плодить лишних колонок, иметь какое-то соглашение, и сортировать по какому-нибудь полю (которое всегда есть), например (RusDescr). 
Можно, завести какое-то поле (порядок вывода).

**Comment by ybinzu** [comment]
Нужно добавить сортировку по `LineDescription.DescriptionRus` в `GetLineDescriptions` + `LineDescriptionDto`.
