### ISSUE TITLE
"Градусник" Уровень Тревоги в LDA

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#52]
В прототипе идея была анализировать массив по величине χ2 как это делается в градуснике. Выше уровень тревоги, (от зеленого, через оранжевый, к красному как это делается в градуснике. Выше "температура" , выше столбик. На конце столбика - расчетная цифра. 

https://www.justinmind.com/usernote/tests/32387290/35551603/35573897/index.html#/screens/20144d51-d524-4f44-8b3b-8fbfddf5cfd0 

![image](https://user-images.githubusercontent.com/36114863/45225593-98ffc300-b2c5-11e8-864f-9ff1dc798807.png)

**Comment by ybinzu** [comment]
Поправил, задеплоил.
