### ISSUE TITLE
Осмысленная подпись оси Х диаграммы распределения последней цифры

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#54]
В идеале, тут должны стоять те параметры, которые анализировались. 
Если пока сложно, просто убрать. Тем более, клик на надписи дает непонятный результат (поле очищается)

![image](https://user-images.githubusercontent.com/36114863/45226376-57701780-b2c7-11e8-8c8a-07b3d9e34b9c.png)

**Comment by ybinzu** [comment]
Скрыл "Series 1"
