### ISSUE TITLE
Скрывать тестовые ProtocolSet

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#56]
Пока контент-менеджер настраивает ProtocolSet или тестирует его, он не должен быть виден обычным пользователям. Флаг visible/hidden или что-то подобное.

**Comment by ybinzu** [comment]
Частично решил тут: https://github.com/GolosMovement/StatElectGenerator/issues/42#issuecomment-419620768

**Comment by ybinzu** [comment]
Задеплоил.
