### ISSUE TITLE
Пользователь видит окончание генерации ProtocolSet'а

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#58]
Сейчас файл уходит в Систему, система довольно долго заполняет базу.
Пользователь должен получать информацию, когда закончена генерация и можно начинать анализ.

 - [x] #63

**Comment by ybinzu** [comment]
Здесь же нужно сделать проверки и не давать начинать импорт в случае ошибок:
 1. присутствие `TitleRus` (проверить, а работает ли Required)
 1. одинаковые имена у разных `ProtocolSet` по `TitleRus` (добавить Unique?)

**Comment by ybinzu** [comment]
Задеплоил.
