### ISSUE TITLE
Ускорить LDA 

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#60]
Обработка в LDA даже небольшого региона (130 записей) по одному параметру занимает более 10 минут (Ингушетия, ProtocolSet Дума 2011 неполн.)

**Comment by rgarifullin** [comment]
Сделали запросы в базу для получения только полей **Id** из **LineDescriptions** и **Value** из **LineNumbers**, в сервис анализатора будет попадать список чисел, а не объектов **LineNumber**.
В среднем максимальное время было 12-15 секунд.
10 минут скорей всего было из-за ошибки, добавили alert уведомление на этот случай.

**Comment by rgarifullin** [comment]
Задеплоили последний коммит.

**Comment by ybinzu** [comment]
Здесь #64 изменил принцип работы с entities на raw sql.
