### ISSUE TITLE
Неизвестная ошибка при получении последней цифры

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#70]
Если анализировать recordset как на картинке, то выдается ошибка в FF и Chrome

![ff](https://user-images.githubusercontent.com/36114863/46463814-7e8a0e00-c7cd-11e8-9ff9-07fc42d854e7.png)
![image](https://user-images.githubusercontent.com/36114863/46463824-8649b280-c7cd-11e8-83c1-3d9d35f01364.png)
![image](https://user-images.githubusercontent.com/36114863/46463832-8c3f9380-c7cd-11e8-8c6c-54aeab3f3438.png)

**Comment by rgarifullin** [comment]
Срабатывает CommandTimeout на стороне базы. Azure троттлит выполнение запросов БД, из-за чего превышается время этого таймаута.
