### ISSUE TITLE
Server failed to fetch

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#78]
Файл https://drive.google.com/open?id=1iaXoGWrA9tc1bazpBQFwSVIWjIMuquGI
Записей (УИК) 97 699
Mapping "Президент РФ 2018"
![image](https://user-images.githubusercontent.com/36114863/46873835-4d01ea00-ce40-11e8-818b-1469081c66dc.png)

Трудно сказать, но повторный импорт, кажется, висит (
![image](https://user-images.githubusercontent.com/36114863/46873928-96523980-ce40-11e8-8ead-41733a2a57b8.png)

Колесико крутится
![image](https://user-images.githubusercontent.com/36114863/46874032-daddd500-ce40-11e8-869c-4cf5adb0866e.png)

**Comment by rgarifullin** [comment]
Похоже на проблему с сетью, сам импорт был завершен успешно.
Повторный импорт не завис, а ожидал очереди на выполнение (т.е. на сервере одновременно существует только 1 задача на импорт).

**Comment by ybinzu** [comment]
Решилось тут: https://github.com/GolosMovement/StatElectGenerator/commit/ff6988a8c9e428d4578380e99806b2bd08b4a741

Заданием `BulkCopyTimeout = 0`
