### ISSUE TITLE
Импорт пустых значений

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#87]
Пустые значения в численных результатах нельзя импортировать как "0". 
При анализе эти "0" дают [неверные результаты](https://github.com/GolosMovement/QA-electoral.graphics/issues/12). 
Причины нахождения "" в числовых данных [оправданы](https://docs.google.com/document/d/10gNc5Cdme6wKCwx4PqKmWaqQ64RuYqxQQQg1WkpmLeE/edit?usp=sharing). 
Мне кажется хорошее решение импортировать как null и отбрасывать null перед анализами.
При экспорте данные будут собираться в исходные без искажений, т.е. где стояло "" при импорте, при экспорте будет также стоять "", а не "0" как сейчас. 

Импорт пустых строковых значений не вызывает таких проблем ни при анализе (который пока не предвидится) ни при экспорте: мы снова получаем "".

**Comment by ybinzu** [comment]
#27
