### ISSUE TITLE
Низкая скорость на product

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/StatElectGenerator#92]
Посмотрите, пожалуйста, индексы.

Подозреваю, что это то, что мы не разгадали 30.10 (если я не ошибаюсь датой).
Скорость падала и поднималась в 10 раз. Мы отыгрывали c помощью DTU в четыре. 

![image](https://user-images.githubusercontent.com/36114863/48629625-d1590700-e9c2-11e8-9298-490a3f87f744.png)
![image](https://user-images.githubusercontent.com/36114863/48629633-d453f780-e9c2-11e8-98e8-4b033cbd4016.png)
![image](https://user-images.githubusercontent.com/36114863/48629638-d6b65180-e9c2-11e8-9faa-11074984edfc.png)
![image](https://user-images.githubusercontent.com/36114863/48629641-d918ab80-e9c2-11e8-9119-5243d0274ff6.png)

Хотя есть небольшая разница в числе записей, она не должна давать такую значительную разницу.

**Comment by ybinzu** [comment]
Это связано с #93, поэтому закрываю.
